# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/111g4Y9gPHIAAj9kLa364qHwgfcbP3hWX
"""

import streamlit as st
import numpy as np
import joblib

# --- Load mô hình ---
model = joblib.load("logistic_asd_model.pkl")

st.set_page_config(page_title="Sàng lọc Tự kỷ người lớn (ASD)", page_icon="🧠")

# --- Giao diện chính ---
st.title("🧠 Hệ thống Sàng lọc Rối loạn phổ Tự kỷ (ASD) cho người lớn")
st.write("Trả lời 10 câu hỏi sau để hệ thống hỗ trợ đánh giá nguy cơ ASD. Kết quả chỉ mang tính hỗ trợ, không thay thế chẩn đoán y tế.")

# --- Danh sách câu hỏi ---
questions = [
    "1. Bạn có thích hoạt động một mình hơn là với người khác không?",
    "2. Bạn thường gặp khó khăn khi duy trì cuộc trò chuyện không?",
    "3. Bạn có hay lặp lại các hành động hoặc thói quen một cách đều đặn không?",
    "4. Bạn có cảm thấy khó chịu khi có sự thay đổi nhỏ trong thói quen hàng ngày?",
    "5. Bạn có nhạy cảm với ánh sáng, âm thanh hoặc kết cấu không?",
    "6. Bạn thường khó hiểu cảm xúc hoặc ý định của người khác không?",
    "7. Bạn có gặp khó khăn khi phải nhìn vào mắt người khác không?",
    "8. Bạn có giỏi ghi nhớ các chi tiết nhỏ hoặc ngày tháng không?",
    "9. Bạn cảm thấy không thoải mái trong các sự kiện xã hội hoặc nơi đông người không?",
    "10. Bạn thích làm việc với máy móc hoặc hệ thống hơn là với con người?"
]

# --- Nhập dữ liệu ---
inputs = []
for q in questions:
    ans = st.radio(q, ['Có', 'Không'], key=q)
    inputs.append(1 if ans == 'Có' else 0)

# --- Dự đoán ---
if st.button("🔍 Dự đoán"):
    X_input = np.array(inputs).reshape(1, -1)
    pred = model.predict(X_input)[0]

    st.subheader("📊 Kết quả sàng lọc:")
    if pred == 1:
        st.error("⚠️ Bạn có dấu hiệu phù hợp với người có nguy cơ Rối loạn phổ Tự kỷ (ASD).")
    else:
        st.success("✅ Bạn hiện không có dấu hiệu rõ ràng liên quan đến ASD.")



    # --- Gợi ý tiếp theo ---
    st.markdown("### 🧭 Gợi ý hành động tiếp theo:")
    if pred == 1:
        st.info("""
        🔹 Hãy liên hệ chuyên gia tâm lý hoặc cơ sở y tế để được tư vấn kỹ lưỡng hơn.
        🔹 Ghi chép lại các biểu hiện thường gặp trong cuộc sống hàng ngày.
        🔹 Có thể tham khảo các tài liệu về ASD từ WHO, CDC hoặc các trung tâm hỗ trợ trong nước.
        """)
    else:
        st.success("""
        ✅ Bạn có thể yên tâm ở thời điểm hiện tại.
        🔹 Việc phát triển kỹ năng xã hội và cảm xúc vẫn ổn.
        🔹 Nếu còn băn khoăn, bạn có thể trao đổi thêm với chuyên gia.
        """)

